module.exports = {
  apps: [
    {
      name: "naashpati-api",
      script: "server.js",
      cwd: "./backend",
      env: {
        NODE_ENV: "development",
        PORT: 5000,
        CLIENT_URLS: "http://localhost:5173,http://localhost:5000,http://localhost:5174,http://localhost:5175,http://localhost:5176,http://localhost:5177,http://localhost:5178,http://localhost:5179,http://localhost:5180",
        CLIENT_URL: "http://localhost:5173",
        MONGODB_URI: "mongodb+srv://admin:311Naashpati113@naashpati.leexkrt.mongodb.net/naashpati_dev?retryWrites=true&w=majority&appName=Naashpati",
        JWT_SECRET: "replace_with_secure_secret",
        JWT_EXPIRE: "30d",
        JWT_REFRESH_SECRET: "replace_with_secure_refresh_secret",
        JWT_REFRESH_EXPIRE: "7d",
        CLOUDINARY_CLOUD_NAME: "your_cloudinary_cloud_name",
        CLOUDINARY_API_KEY: "your_cloudinary_api_key",
        CLOUDINARY_API_SECRET: "your_cloudinary_api_secret",
        GCS_KEY_FILE: "./config/gcs-service-account.json",
        GCS_PROJECT_ID: "naashpati",
        GCS_BUCKET_NAME: "my-ecommerce-products",
        STRIPE_SECRET_KEY: "your_stripe_secret_key",
        STRIPE_PUBLISHABLE_KEY: "your_stripe_publishable_key",
        SMTP_HOST: "smtp.gmail.com",
        SMTP_PORT: 587,
        SMTP_EMAIL: "your_email@gmail.com",
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 5000,
        CLIENT_URLS: "https://naashpati.com",
        MONGODB_URI: "mongodb+srv://admin:311Naashpati113@naashpati.leexkrt.mongodb.net/naashpati?retryWrites=true&w=majority&appName=Naashpati",
        JWT_SECRET: "48593b9fe7926f61747d5d6f9a8189266015de4019420228a49d90ffa5176016",
        JWT_EXPIRE: "30d",
        JWT_REFRESH_SECRET: "95c633395e6349383685566468be70f1f36eb44c8c932d36da76170492625a03",
        JWT_REFRESH_EXPIRE: "7d",
        EMAIL_VERIFICATION_EXPIRE_MINUTES: 60,
        LOGIN_MAX_ATTEMPTS: 5,
        LOGIN_LOCK_MINUTES: 15,
        TWO_FACTOR_CODE_EXPIRE_MINUTES: 10,
        SMTP_HOST: "smtp.hostinger.com",
        SMTP_PORT: 587,
        SMTP_EMAIL: "noreply@naashpati.com",
        SMTP_PASSWORD: "@,11Noreply11,@",
        FROM_NAME: "Naashpati",
        FROM_EMAIL: "noreply@naashpati.com",
        CLOUDINARY_CLOUD_NAME: "dwu2akcot",
        CLOUDINARY_API_KEY: "484378186926149",
        CLOUDINARY_API_SECRET: "SQxrT_NEAx2FoC94bhWRdbdvdBg",
      },
    },
  ],
};
